package com.astix.Common;

import android.net.Uri;
import java.io.File;

public class CommonInfo {
	public static String ActiveRouteSM = "0";
	public static int AnyVisit = 0;
	public static String AppLatLngJsonFile = "ParasSFALatLngJson";

	public static int Application_TypeID = 8;
	public static final String AttandancePreference = "ParasAttandancePreference";
	public static int CoverageAreaNodeID = 0;
	public static int CoverageAreaNodeType = 0;
	public static String DATABASE_NAME = "DbParasSFAApp";
	public static int DATABASE_VERSIONID = 22;
	public static String AppVersionID = "1.15";
	public static int DayStartClick = 0;
	public static int DistanceRange = 3000;
	public static final String DistributorCheckInXMLFolder = "ParasDistributorCheckInXML";
	public static final String DistributorMapXMLFolder = "ParasDistributorMapXML";
	public static final String DistributorStockXMLFolder = "ParasDistributorStockXML";
	public static String DistributorSyncPath = "http://103.20.212.194/ReadXML_ParasSFADistributionDevelopment/Default.aspx";
	public static String FinalLatLngJsonFile = "ParasSFAFinalLatLngJson";
	public static int FlgDSRSO = 0;
	public static String ImageSyncPath = "http://103.20.212.194/ReadXML_ParasImagesDevelopment/Default.aspx";
	public static String ImagesFolder = "ParasSFAImages";
	public static String ImagesFolderServer = "PARASSFAImagesServer";
	public static String InvoiceSyncPath = "http://103.20.212.194/ReadXML_ParasInvoiceDevelopment/Default.aspx";
	public static String InvoiceXMLFolder = "ParasInvoiceXml";
	public static String OrderSyncPath = "http://103.20.212.194/ReadXML_ParasDevelopment/DefaultSFA.aspx";
	public static String OrderSyncPathDistributorMap = "http://103.20.212.194/ReadXML_ParasLive/DefaultSODistributorMapping.aspx";
	public static String OrderTextSyncPath = "http://103.20.212.194/ReadTxtFileForParasSFADev/default.aspx";
	public static String OrderXMLFolder = "ParasSFAXml";
	public static final String Preference = "ParasPrefrence";
	public static String SalesPersonTodaysTargetMsg = "";
	public static String SalesQuoteId = "BLANK";
	public static int SalesmanNodeId = 0;
	public static int SalesmanNodeType = 0;
	public static String TextFileFolder = "ParasTextFile";
	public static String VersionDownloadAPKName = "ParasSFA_Dev.apk";
	public static String VersionDownloadPath = "http://103.20.212.194/downloads/";
	public static String WebServicePath = "http://103.20.212.194/WebServiceAndroidParasDevelopment/Service.asmx";
	public static String WebStockInUrl = "http://103.20.212.194/Parassfa/manageorder/frmstockin.aspx";
	public static String WebStockOutUrl = "http://103.20.212.194/Parassfa/manageorder/frmStockTransferToVanDetail_PDA.aspx";
	public static String clickedTagPhoto_savedInstance = null;
	public static String fileContent = "";
	public static int flgAllRoutesData = 1;
	public static int flgDataScope = 0;
	public static String globalValueOfPaymentStage = "0_0_0";
	public static File imageF_savedInstance = null;
	public static String imageName_savedInstance = null;
	public static String imei = "";
	public static int VanLoadedUnloaded = 0;
	public static String newQuottionID = "NULL";
	public static String prcID = "NULL";
	public static String quatationFlag = "";
	public static String sPrefVanLoadedUnloaded = "VanLoadedUnloaded";
	public static Uri uriSavedImage_savedInstance = null;
}
